### ISSUE TITLE
preview crashes for all Views when I load library via SPM (Xcode 14 beta 5)

### ISSUE THREAD

**Issue by akardas16** [movingparts-io/Pow#6] opened 2022-08-23 12:17 UTC

**Comment by robb** [comment] 2022-08-23 17:59
Yeah, that's a [Known Issue](https://github.com/movingparts-io/Pow/tree/db9a2ed32f1277446a6fbad9f29abdd78e049151#known-issues), unfortunately. I'm hoping Apple will resolve this problem as there are [quite a few people](https://developer.apple.com/forums/thread/707569) affected by this. Since it appears to work fine in Xcode 13, I'm inclined to consider this a regression on Xcode's side.

If you download the `.xcframework` file linked in the `Package.swift`, you can drag that into your project manually in which case the issue seems to resolve itself.

**Comment by robb** [comment] 2022-11-04 16:35
This seems to have been fixed as of Xcode 14.1 beta (14B5024h) – @akardas16 can yo confirm?

**Comment by robb** [comment] 2022-11-14 11:16
Confirmed this no longer is a problem as of Xcode 16.1 🎉

**Closed by robb** 2022-11-14 11:16 UTC
